### ISSUE TITLE
ES6 Import doesn't work for me

### ISSUE THREAD

**Issue by samw1989** [ndaidong/article-parser#206] opened 2021-12-27 04:52 UTC
Hello, very new to Javascript, so apologies if I'm just misunderstanding and this isn't a bug. 

Per the documentation, I ran:

 `import { extract } from 'article-parser'`

This doesn't work for me. It leads to:

`SyntaxError: Named export 'extract' not found. The requested module 'article-parser' is a CommonJS module, which may not support all module.exports as named exports.`

Running _import main from 'article-parser'_, and then calling main.extract() does work.

**Comment by ndaidong** [comment] 2021-12-27 07:20
@samw1989 hello, thank you for your report. Which runtime/platform are you working on?

**Comment by samw1989** [comment] 2021-12-27 15:16
Node.js (v15).

**Comment by ndaidong** [comment] 2021-12-27 16:04
@samw1989 do you use TypeScript or [esm](https://www.npmjs.com/package/esm), or run your server with `–experimental-modules` flag?
By default, the latest versions of Node.js do not support native ES6 module import/export syntax yet.

**Comment by samw1989** [comment] 2022-01-01 00:29
Sorry for delayed response. Yes, running modular system using "type": "module".

I tried switching to CommonJS and require() works just fine. Only the ES6 import that is causing me trouble.

**Comment by ndaidong** [comment] 2022-01-02 03:09
@samw1989 I will try to rewrite to use es6 module syntax instead of commonjs.

**Comment by SettingDust** [comment] 2022-02-05 05:35
> @samw1989 I will try to rewrite to use es6 module syntax instead of commonjs.

https://github.com/SettingDust/article-parser Something I did for es6 xd. But not for current version

**Comment by ndaidong** [comment] 2022-02-05 07:52
@SettingDust last month, I've created branch [es6-module-format](https://github.com/ndaidong/article-parser/tree/es6-module-format), and could not pass the test. The problem occurred with jsdom module.

https://github.com/ndaidong/article-parser/commit/3999e810883e086807bd5b2578672fa1b8a64e91

Do you have any suggestion?

**Comment by SettingDust** [comment] 2022-02-05 08:32
> Do you have any suggestion?

I've not runned into error
```
Test Suites: 14 passed, 14 total
Tests:       70 passed, 70 total
Snapshots:   0 total
Time:        8.662 s, estimated 14 s
Ran all test suites.
```

**Comment by ndaidong** [comment] 2022-02-05 08:39
@SettingDust  I see that your fork is quite far from my current version and you had added a lot of modifications, so they could not be merged easily.

**Comment by SettingDust** [comment] 2022-02-05 08:41
> @SettingDust I see that your fork is quite far from my current version and you had added a lot of modifications, so they could not be merged easily.

I mean your branch not run into error on my end

**Comment by ndaidong** [comment] 2022-02-05 12:58
@SettingDust at my local environment, it works as well too :)
It just doesn't pass the github CI. Anw, I will investigate the root cause here.

**Comment by SettingDust** [comment] 2022-02-05 13:22
Just `npm i canvas`. But `canvas` is depends on native module which `esbuild` not support. Maybe need switch to `webpack` or `rollup` etc.

**Comment by ndaidong** [comment] 2022-02-05 13:35
@SettingDust if so, rollup may help. Let's me try with Rollup to see if it works for us.

**Comment by SettingDust** [comment] 2022-02-05 13:44
> @SettingDust if so, rollup may help. Let's me try with Rollup to see if it works for us.

I'm trying to use rollup for building now

**Comment by SettingDust** [comment] 2022-02-05 14:11
> Just `npm i canvas`. But `canvas` is depends on native module which `esbuild` [not support](https://github.com/evanw/esbuild/issues/1051). Maybe need switch to `webpack` or `rollup` or `parcel` etc.

It's seems that we won't use the `canvas`? Maybe we should exclude it from building. So that `esbuild` can work

**Comment by ndaidong** [comment] 2022-02-05 14:18
Thank you for your notice. I'm not sure if `canvas` being used. My idea is:

- standard es6 module format as default, without compiling, just import and use. So we don't care about `canvas`.
- generated commonjs version for the rest, because many projects are being stuck at the outdated Node.js environments, not easy to upgrade.

**Comment by SettingDust** [comment] 2022-02-05 14:21
> Thank you for your notice. I'm not sure if `canvas` is being used. My idea is:
> 
>     * standard es6 module format as default, without compiling, just import and use. So we don't care about `canvas`.
> 
>     * generated commonjs version for the rest, because many projects are being stuck at the outdated Node.js environments, not easy to upgrade.

`canvas` is a native module. So there is a file which named `canvas.node`. Can't be bundled

**Comment by ndaidong** [comment] 2022-02-05 14:25
@SettingDust I think `canvas` is only available in browser environment, not native at Node.js platform yet. `jsdom` wants to mimic some browser behaviors, so it needs to something to simulate HTML Canvas API.

**Comment by SettingDust** [comment] 2022-02-05 14:27
> @SettingDust I think `canvas` is only available in browser environment, not native at Node.js platform yet. `jsdom` wants to mimic some browser behaviors, so it needs something to simulate HTML Canvas API.

Yes, it's that. So, for user who want to parse canvas as well. They should install it in their project I think

**Comment by ndaidong** [comment] 2022-02-05 14:44
@SettingDust It seems we have to wait for a while, until ES6 Module becomes more regular. More dependencies, more complicate to migrate. I've done with several public repos here, but sometimes these changes also cause unnecessary troubles!

**Comment by SettingDust** [comment] 2022-02-05 14:52
> @SettingDust It seems we have to wait for a while, until ES6 Module becomes more regular. More dependencies, more complicate to migrate. I've done with several public repos here, but sometimes these changes also cause unnecessary troubles!

In fact, the main branch depends on `jsdom -> canvas`, too. Just the `esbuild` want to parse the `canvas`. If set it as `external`. It's totally as same as main branch behavior (users need to install `canvas` themselves)

**Comment by SettingDust** [comment] 2022-02-05 14:57
It's ok now. https://github.com/ndaidong/article-parser/pull/212

**Comment by ndaidong** [comment] 2022-02-05 15:01
@SettingDust cool! I will merge, but keep it as rc version for right now.
`standard` will be installed with CI config, so we don't need to have it as `devDependencies`.

**Comment by SettingDust** [comment] 2022-02-05 15:05
> @SettingDust cool! I will merge, but keep it as rc version for right now. `standard` will be installed with CI config, so we don't need to have it as `devDependencies`.

Run with npx not need to install global in local and ci

**Comment by ndaidong** [comment] 2022-02-05 15:36
@SettingDust I'm testing at local environment. ES6 version works as well, however commonjs version doesn't work yet!

ES6 evaluation:

![Screenshot from 2022-02-05 22-34-31](https://user-images.githubusercontent.com/1809619/152648286-9721cf4c-5708-40bb-b0e5-fa0ed1534916.png)

CommonJS version:

![Screenshot from 2022-02-05 22-34-13](https://user-images.githubusercontent.com/1809619/152648304-880861bb-c633-4305-9251-8b57b364fb4f.png)

**Comment by SettingDust** [comment] 2022-02-06 15:03
> @SettingDust I'm testing at local environment. ES6 version works as well, however commonjs version doesn't work yet!
> 
> ES6 evaluation:
> 
> ![Screenshot from 2022-02-05 22-34-31](https://user-images.githubusercontent.com/1809619/152648286-9721cf4c-5708-40bb-b0e5-fa0ed1534916.png)
> 
> CommonJS version:
> 
> ![Screenshot from 2022-02-05 22-34-13](https://user-images.githubusercontent.com/1809619/152648304-880861bb-c633-4305-9251-8b57b364fb4f.png)

Caused by esbuild not support dynamic import from https://github.com/ndaidong/article-parser/blob/main/src/utils/chooseBestUrl.js#L18

**Comment by ndaidong** [comment] 2022-02-11 03:43
@SettingDust thank you, if so, I think we should keep it there, the issue will be fixed by itself :smile:

**Comment by SettingDust** [comment] 2022-02-12 03:00
> @SettingDust thank you, if so, I think we should keep it there, the issue will be fixed by itself 😄

Maybe we can disable the string comparison algorithm option temporary? Publish a version like 6.0.0-alpha

**Comment by ndaidong** [comment] 2022-02-12 03:15
@SettingDust string comparison is needed to predict the best URL of article (with it we can normalize the images path too). I consider the trade-off to be not worth it.

**Comment by SettingDust** [comment] 2022-02-12 05:01
> 

Needn't remove entire module. Just [disable the option](https://github.com/ndaidong/article-parser/blob/es6-module-format/src/config.js#L57) to change algorithm with default `levenshtein`.

**Comment by ndaidong** [comment] 2022-02-13 05:12
@SettingDust I've merge you pr #217 , let's check if it works for us in several more tests.

**Comment by SettingDust** [comment] 2022-02-13 05:13
> @SettingDust I've merge you pr #217 , let's check if it works for us in several more tests.

Haven't repair the cjs dist issue

**Comment by ndaidong** [comment] 2022-02-13 05:49
@SettingDust yes, while using cjs version, I face problem with `string-comparison`:

![Screenshot from 2022-02-13 12-43-34](https://user-images.githubusercontent.com/1809619/153740638-40d89629-04aa-40e2-8365-97497f1898b4.png)

I found a workaround by copying a part of this lib to dist folder.

**Comment by ndaidong** [comment] 2022-02-13 05:55
@SettingDust I just released v6.0.0-rc1, let's give it a try. When we feel it's reliable enough, it will be merged into main branch.

**Comment by SettingDust** [comment] 2022-02-13 08:35
> @SettingDust I just released v6.0.0-rc1, let's give it a try. When we feel it's reliable enough, it will be merged into main branch.

It's not caused by the dynamic import, MB. I'm looking into the esbuild

**Comment by SettingDust** [comment] 2022-02-13 09:11
Weird. It's can build without any changes. Maybe it is fixed by itself. It's seems that a "Quantum" lul.
I read `string-comparison`'s code https://github.com/Rabbitzzc/js-string-comparison/blob/master/lib/index.js. The modules aren't import with ``main/packages/${module}``. But what we meetting says it use a dynamic import.
But, I noticed that https://github.com/Rabbitzzc/js-string-comparison/commit/8eafa55801b11bf5f5f66fbe46fe4d6a7b07badf. This commit remove the dynamic import part. 
How dare esbuild build with an older version? Then I try to clear the package and `npm i` again. Well, it's fine now.

**Comment by ndaidong** [comment] 2022-02-14 10:15
@SettingDust thank you for pointing out, I will merge your latest pr now.

**Comment by ndaidong** [comment] 2022-02-14 10:45
@SettingDust I don't know why but without my workaround, the issue is still happening 

![Screenshot from 2022-02-14 17-41-06](https://user-images.githubusercontent.com/1809619/153848999-dc0bc0a0-e94a-466a-8b0d-6d8b8149976c.png)

Could you try there step:

```bash
npm run reset  # to clean everything
npm i

# temporarily remove `"type": "module"` within package.json, then
npm run eval:cjs https://www.detroitnews.com/story/news/local/detroit-city/2022/02/13/ambassador-bridge-protesters-arrests-blockade-border/6775095001/
```

**Comment by SettingDust** [comment] 2022-02-14 11:14
> @SettingDust I don't know why but without my workaround, the issue is still happening
> 
> ![Screenshot from 2022-02-14 17-41-06](https://user-images.githubusercontent.com/1809619/153848999-dc0bc0a0-e94a-466a-8b0d-6d8b8149976c.png)
> 
> Could you try there step:
> 
> ```shell
> npm run reset  # to clean everything
> npm i
> 
> # temporarily remove `"type": "module"` within package.json, then
> npm run eval:cjs https://www.detroitnews.com/story/news/local/detroit-city/2022/02/13/ambassador-bridge-protesters-arrests-blockade-border/6775095001/
> ```

He havent published his changes with a tag. We need use the github source for package.

**Comment by Rabbitzzc** [comment] 2022-02-18 09:09
my bad

**Comment by Rabbitzzc** [comment] 2022-02-18 11:41
I published the version `1.1.0`, please update to this version and try it.

**Comment by ndaidong** [comment] 2022-02-19 10:29
@Rabbitzzc thank you so much! I'm worrying you've forgot it.

**Comment by ndaidong** [comment] 2022-02-19 10:40
@SettingDust v6.0.0rc4 has been released. If nothing wrong, we can merge to main branch next week.

**Closed** 2022-03-03 05:12 UTC
